version: "3"

services:
  discovery:
    image: kms/discovery
    container_name: discovery
    restart: always
    build:
      context: ./discovery
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    entrypoint:
      [
        "java",
        "-Xmx64m",
        "-Xss512k",
        "-jar",
        "-Dserver.port=8761",
        "-Dspring.profiles.active=staging",
        "-Djava.security.egd=file:/dev/./urandom",
        "/app.jar",
      ]

  configserver:
    image: kms/configserver
    container_name: configserver
    build:
      context: ./configserver
      dockerfile: Dockerfile
    environment:
      - DISCOVERY_SERVER_HOST=discovery
    ports:
      - "9090:9090"
    depends_on:
      - discovery
    command:
      [
        "./wait-for-it.sh",
        "discovery:8761",
        "--",
        "java",
        "-Xmx64m",
        "-Xss512k",
        "-jar",
        "-Dserver.port=9090",
        "-Dspring.profiles.active=staging",
        "-Djava.security.egd=file:/dev/./urandom",
        "/app.jar",
      ]
    links:
      - discovery:discovery

  calculator:
    image: kms/calculator
    container_name: calculator
    build:
      context: ./calculator
      dockerfile: Dockerfile
    environment:
      - DISCOVERY_SERVER_HOST=discovery
      - CONFIG_SERVER_HOST=configserver
    ports:
      - "8080:8080"
    depends_on:
      - discovery
      - configserver
    command:
      [
        "./wait-for-it.sh",
        "configserver:9090",
        "--",
        "java",
        "-Xmx64m",
        "-Xss512k",
        "-jar",
        "-Dserver.port=8080",
        "-Dspring.profiles.active=staging",
        "-Djava.security.egd=file:/dev/./urandom",
        "/app.jar",
      ]
    links:
      - discovery:discovery
      - configserver:configserver

  simulation:
    image: kms/simulation
    container_name: simulation
    build:
      context: ./simulation
      dockerfile: Dockerfile
    environment:
      - DISCOVERY_SERVER_HOST=discovery
      - CONFIG_SERVER_HOST=configserver
    ports:
      - "8090:8090"
    depends_on:
      - discovery
      - configserver
      - calculator
    command:
      [
        "./wait-for-it.sh",
        "calculator:8080",
        "--",
        "java",
        "-Xmx64m",
        "-Xss512k",
        "-jar",
        "-Dserver.port=8090",
        "-Dspring.profiles.active=staging",
        "-Djava.security.egd=file:/dev/./urandom",
        "/app.jar",
      ]
    links:
      - discovery:discovery
      - configserver:configserver
      - calculator:calculator

  gateway:
    image: kms/gateway
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    environment:
      - DISCOVERY_SERVER_HOST=discovery
      - CONFIG_SERVER_HOST=configserver
    ports:
      - "9091:9091"
    depends_on:
      - discovery
      - configserver
    command:
      [
        "./wait-for-it.sh",
        "simulation:8090",
        "--",
        "java",
        "-Xmx64m",
        "-Xss512k",
        "-jar",
        "-Dserver.port=9091",
        "-Dspring.profiles.active=staging",
        "-Djava.security.egd=file:/dev/./urandom",
        "/app.jar",
      ]
    links:
      - discovery:discovery
      - configserver:configserver
