version: "2"

services:
  discovery:
    image: kms/discovery
    container_name: discovery
    restart: always
    build:
      context: ./discovery
      dockerfile: Dockerfile
    ports:
      - 8761:8761

  configserver:
    image: kms/configserver
    container_name: configserver
    build:
      context: ./configserver
      dockerfile: Dockerfile
    environment:
      - DISCOVERY_SERVER_HOST=discovery
    ports:
      - "9090:9090"
    depends_on:
      - discovery
    command: >
      /bin/bash -c "
        while ! nc -z discovery 8761;
        do
          echo sleeping;
          sleep 1;
        done;
        echo Connected!;
      "
    links:
      - discovery:discovery

  calculator:
    image: kms/calculator
    container_name: calculator
    build:
      context: ./calculator
      dockerfile: Dockerfile
    environment:
      - DISCOVERY_SERVER_HOST=discovery
      - CONFIG_SERVER_HOST=configserver
    ports:
      - "8080:8080"
    depends_on:
      - discovery
      - configserver
    links:
      - discovery:discovery
      - configserver:configserver
    command: >
      /bin/bash -c "
        while ! nc -z discovery 8761;
        do
          echo sleeping;
          sleep 1;
        done;
        while ! nc -z configserver 9090;
        do
          echo sleeping;
          sleep 1;
        done;        
        echo Connected!;
      "
  # simulation:
  #   image: kms/simulation
  #   container_name: simulation
  #   build:
  #     context: ./simulation
  #     dockerfile: Dockerfile
  #   environment:
  #     - DISCOVERY_SERVER_HOST=discovery
  #   ports:
  #     - "8090:8090"
  #   depends_on:
  #     - discovery
  #     - config
  #     - gateway
  #     - calculator
  #   links:
  #     - discovery:discovery
  #     - configserver:configserver
  #     - gateway:gateway
  #     - calculator:calculator
  #   tty: true
  #   restart: unless-stopped
