Server:
  port: 8080
spring:
  application:
    name: "calculator"
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:9090

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

app:
  configuration:
    cet:
      daysInMonth: 30
      daysInYear: 30

